database:
  host: "temporaltest.cz6q8kq4i3qr.us-east-1.rds.amazonaws.com"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "postgres"
  sslmode: "require"
  pool:
    max_conns: 20
    min_conns: 5
    max_conn_lifetime: 30m
    max_conn_idle_time: 10m

temporal:
  host_port: "18.208.242.118:7233"
  namespace: "default"

workflow_count: 1000
activity_count: 20
task_queue: "go-poc"
