database:
  host: "localhost"
  port: 5433
  user: "postgres"
  password: "password"
  dbname: "test"
  sslmode: "disable"
  pool:
    max_conns: 20
    min_conns: 5
    max_conn_lifetime: 30m
    max_conn_idle_time: 10m

temporal:
  host_port: "localhost:7233"
  namespace: "default"

workflow_count: 100
activity_count: 20
task_queue: "go-poc"
