database:
  host: "3.223.16.235"
  port: 4444
  user: "postgres"
  password: "password"
  dbname: "postgres"
  sslmode: "disable"
  pool:
    max_conns: 20
    min_conns: 5
    max_conn_lifetime: 30m
    max_conn_idle_time: 10m

temporal:
  host_port: "18.208.242.118:7233"
  namespace: "default"

workflows:
  count: 100
  batchSize: 100
  parallelism: 32
  throttleDelayMs: 100
  RetryCount: 20
  executionTimeout: 12000

workers:
  workflowWorkerCount: 200
  activityWorkerCount: 200

activities:
  StartToCloseTimeout: 100000
  ScheduledToCloseTimeout: 200000
  StartToScheduleTimeout: 10000
  RetryCount: 30
  heartbeatIntervalSeconds: 10
  initialInterval: 1
  maximumInterval: 100000
  backoffCoefficient: 2.0
  count: 20

task_queue: "go-poc"
